### ISSUE TITLE
Should we file an issue in waffle to make this the supported gcs package

### ISSUE THREAD

**Issue by dlobo** [almirsarajcic/waffle_gcs#12]
We should check if the waflle project leads are willing to change the links to this package to make it the supported gcs package. We can then rename it and post it to hexdocs, which will make life easier for all of us and those coming later

@almirsarajcic would you be interested in doing so?

**Comment by almirsarajcic** [comment]
Thanks, I'll mention the owners in the original issue.

**Comment by almirsarajcic** [comment]
https://github.com/kolorahl/waffle_gcs is active again.
