### ISSUE TITLE
Hex.pm and Waffle pointing to old GitHub repository

### ISSUE THREAD

**Issue by ulissesalmeida** [almirsarajcic/waffle_gcs#22]
👋🏽 Hi, I don't know if you're aware. But the Hex.PM and the Waffle GitHub is pointing to https://github.com/tyler-eon/waffle_gcs

**Comment by almirsarajcic** [comment]
Hi @ulissesalmeida.
Thanks for pointing it out and for the other comments/PRs you've made.

I haven't used waffle_gcs or Google Cloud Storage for a long time, so I've lost the incentive to maintain this project.
I see you're involved deeply with the waffle_gcs package, so if you're interested, I can transfer you its ownership on Hex.pm.

**Comment by ulissesalmeida** [comment]
Thank you for the invite. The company I'm working at the moment uses GCS for minor things, so it's not a huge interest for me to maintain it. However, at the same time the library seems to be pretty stable.

@petermueller did review my goth PR, and seems to be an active participant before me. If @petermueller is interested I think Peter would a better candidate. If not, I would be happy to take the responsibility to apply the fixes that we need and do the goth upgrade, review and patch minor fixes.

**Comment by petermueller** [comment]
I'd be happy to maintain or co-maintain w/ @ulissesalmeida.
I've a couple young kids, so I'm not sure me being the sole-maintainer would be advisable.

Would you be interested in something like that, @ulissesalmeida?

**Comment by ulissesalmeida** [comment]
Yes! Much better!

**Comment by petermueller** [comment]
@almirsarajcic, let me know if that's cool with you, and how you'd like us to handle where the repo lives :)

Edit: I recreated a new hex.pm account (I forgot you can't change old usernames). It's https://hex.pm/users/petermueller

**Comment by almirsarajcic** [comment]
I've transferred the hex package ownership to you, @petermueller, and requested to transfer the ownership of the repo.
Thanks to both you and @ulissesalmeida for taking care of it.

**Comment by ulissesalmeida** [comment]
My hex.pm user is: https://hex.pm/users/ulissesalmeida

In case you want to share the management roles
