### ISSUE TITLE
Making the file public?

### ISSUE THREAD

**Issue by lstrzebinczyk** [almirsarajcic/waffle_gcs#6]
@almirsarajcic Hi!

I need my files to become public when uploading, which is consistent to performing the uploads like this:

```
        ) :: object_or_error
  defp insert(conn, bucket, name, {:file, path}, acl) do
    Objects.storage_objects_insert_simple(
      conn,
      bucket,
      "multipart",
      %Object{name: name, acl: acl},
      path,
      predefinedAcl: "publicRead"
    )
  end
```

Specifically, I am used to setting `predefinedAcl` as `"publicRead"`. Can I get the same effect in some way with current implementation, or do I need to open a PR that will let me set `predefinedAcl` on a request like this?

**Comment by almirsarajcic** [comment]
Have you tried passing `:acl` option to `gcs_object_headers` function (https://github.com/almirsarajcic/waffle_gcs#gcs-object-headers)?

**Comment by lstrzebinczyk** [comment]
Ok then. When I set:

```
  def gcs_object_headers(_version, {_file, _scope}) do
    [acl: "publicRead"]
  end
```

I still get:

![Firefox_Screenshot_2020-09-28T13-37-37 487Z](https://user-images.githubusercontent.com/1272828/94439318-8d2f1400-01a0-11eb-91f3-468cf60d62a2.png)

Which says `non-public` for all uploaded files.

**Comment by almirsarajcic** [comment]
My bad, ACL is set via definition module attribute `@acl` (https://hexdocs.pm/waffle/Waffle.Storage.S3.html#module-access-control-permissions). It seems it's similar for both S3 and GCS as `@acl` is used in `waffle_gcs` here https://github.com/almirsarajcic/waffle_gcs/blob/master/lib/waffle/storage/google/cloud_storage.ex#L33.

**Comment by lstrzebinczyk** [comment]
@almirsarajcic that does not seem to be doing the trick, files get set as private still.

**Comment by almirsarajcic** [comment]
@lstrzebinczyk you'll need to experiment with `google_api_storage` library to see what properties need to be set for the file to be public.

**Comment by lstrzebinczyk** [comment]
@almirsarajcic  I did mention that in the beginning, what I do in other parts of my codebase is 
```
  defp insert(conn, bucket, name, {:file, path}, acl) do
    Objects.storage_objects_insert_simple(
      conn,
      bucket,
      "multipart",
      %Object{name: name, acl: acl},
      path,
      predefinedAcl: "publicRead"
    )
  end
```

Notice the last argument. Waffle isn't setting this up. Would you like me to open a PR that would set this up if `@acl :public_read` is set on the definition?

**Comment by almirsarajcic** [comment]
I think we should rather make this configurable in case other options need to be changed as well.

Would you be willing create a PR that would enable having additional function, like that one `gcs_object_headers/2` which would provide additional options to be passed as the 6th param in that call?

**Comment by lstrzebinczyk** [comment]
Sure thing, I'll provide a PR tomorrow.

**Comment by lstrzebinczyk** [comment]
@almirsarajcic fyi I did https://github.com/almirsarajcic/waffle_gcs/pull/7

; D

**Comment by almirsarajcic** [comment]
Well done!
👍
